services:
  uptime-kuma:
    image: louislam/uptime-kuma:2-slim
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - ./config:/app/data
    ports:
      - 80:3001
    restart: always
