#!/bin/sh

# This is a FreeBSD service file which runs glances in webserver mode

. /etc/rc.subr

name="glances"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

# glances program location
glances_bin="/root/.local/bin/glances"

glances_start()
{
  echo "Starting glances webserver"
  "${glances_bin}" -w -B 0.0.0.0 -p 61208 &
}

glances_stop()
{
  echo "Stopping glances webserver"
  pkill -f "${glances_bin} -w -B 0.0.0.0 -p 61208"
}

load_rc_config "${name}"
run_rc_command "$1"
